apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: products
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (100m)
      targetAverageUtilization: 99