apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: frontend
  service:
    # container port
    port: 9898
    # Istio gateways (optional)
    gateways:
    - istio-system/public-gateway
    # Istio virtual service host names (optional)
    hosts:
    - "*"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    maxWeight: 70
    stepWeight: 10
    # canary match condition
    match:
      #- headers:
      #    user-agent:
      #      regex: ".*Firefox.*"
      #      #regex: "^(?!.*(?:Chrome|Edge)).*Safari"
      - headers:
          cookie:
            regex: "^(.*?;)?(type=insider)(;.*)?$"
    # Istio Prometheus checks
    metrics:
      - name: error-rate
        templateRef:
          name: error-rate
          namespace: istio-system
        thresholdRange:
          max: 1
        interval: 30s
      - name: latency
        templateRef:
          name: latency
          namespace: istio-system
        thresholdRange:
          max: 500
        interval: 30s
    # tests
    webhooks:
      - name: conformance-test
        type: pre-rollout
        timeout: 15s
        url: http://flagger-loadtester.loadtest/
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://frontend-canary.workload-progressive:9898/token | grep token"
      - name: load-test
        type: rollout
        timeout: 15s
        url: http://flagger-loadtester.loadtest/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 -H 'Cookie: type=insider' http://frontend.workload-progressive:9898/"