apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-istio-canary
spec:
  releaseName: workload-istio-canary
  chart:
    spec:
      chart: charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    tolerations:
    - key: "graviton2"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/arch: arm64
    ui:
      message: "Powered by EC2 on Graviton2"
      logo: "https://github.com/cncf/artwork/raw/master/projects/kubernetes/icon/color/kubernetes-icon-color.png"
      color: "#fe9900" ##0065af
    replicaCount: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - workload-istio-canary-podinfo
            topologyKey: topology.kubernetes.io/zone
          weight: 100
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - workload-istio-canary-podinfo
            topologyKey: kubernetes.io/hostname 
          weight: 99